db: "/home/akizenko/Apps/pia3_amphipod_opsins/PIA3/classification_opsins_full_aa.fasta"
in_dir: "/home/akizenko/Apps/pia3_amphipod_opsins/PIA3/test_data"
out_dir: "/home/akizenko/Apps/pia3_amphipod_opsins/PIA3/test_out"
model: "'LG+F+G4'"
outgroup: ""
cd_h: 0.95
opsin: False
bit_score: 40
clean: True
transcripts: "cds"