import os
import pathlib
from snakemake.utils import validate

configfile: "config.yaml"


#validate(config, 'config.schema.yaml')

#workdir: out_dir

#fasta_names ='\.fasta|\.fna|\.ffn|\.fa|\.fsa_nt'
out_dir = config["out_dir"]
in_dir = config["in_dir"]
db = config["db"]
model = config["model"]
outgroup = config["outgroup"]
cd_h = config["cd_h"]
opsin = config["opsin"]
bit_score = config["bit_score"]
clean = config['clean']
transcripts = config["transcripts"]

queries = [os.path.splitext(i)[0] for i in os.listdir(in_dir)]

workdir: out_dir

rule all:
    input: "mad_distances_db_contree.txt", expand("{query}/{query}_db_align.fasta", query=queries)

rule mafft_align_db_seqs:
    input: db
    output: "db_align.fasta"
    benchmark: "benchmarks/mafft_align_db_seqs.txt"
    conda: "pia3.yml"
    log: "logs/mafft_align_db_seqs.txt"
    threads: 8
    shell: "mafft --thread {threads} --auto {input} > {output}"

rule iqtree_build_db_tree:
    input: "db_align.fasta"
    output: "db_align.fasta.contree"
    benchmark: "benchmarks/iqtree_build_db_tree.txt"
    conda: "pia3.yml"
    log: "logs/iqtree_build_db_tree.txt"
    params: bb=1000,
            model="'LG+F+G4'",
            nt="AUTO",
            t="RANDOM"
    threads: 8
    shell: "iqtree -s {input} -nt {params.nt} -t {params.t} -bb {params.bb} -m {params.model} 2> {log}"

rule transdecoder_find_cds:
    input: lambda wildcards: f"{in_dir}/{wildcards.query}.fasta"
    output: "{query}/{query}.fasta.transdecoder_underscores.pep"
    benchmark: "benchmarks/transdecoder_find_cds_{query}.txt"
    conda: "pia3.yml"
    log: "logs/transdecoder_find_cds_{query}.txt"
    threads: 2
    shell: """
            cd {wildcards.query}
            TransDecoder.LongOrfs -t {input}
            TransDecoder.Predict -t {input} --single_best_only
            sed 's/[|,~,/,\,]/_/g' {wildcards.query}.fasta.transdecoder.pep > {wildcards.query}.fasta.transdecoder_underscores.pep
            """

rule blast_search_hits:
    input: lambda wildcards: f"{wildcards.query}/{wildcards.query}.fasta.transdecoder_underscores.pep"
    output: "{query}/{query}_blast_hits.fasta"
    benchmark: "benchmarks/blast_search_hits_{query}.txt"
    conda: "pia3.yml"
    log: "logs/blast_search_hits_{query}.txt"
    threads: 8
    shell: """
            cd {wildcards.query}
            makeblastdb -in {wildcards.query}.fasta.transdecoder_underscores.pep -out {wildcards.query}_blast_db -parse_seqids -dbtype prot
            blastp -query {db} -db {wildcards.query}_blast_db -num_threads {threads} -outfmt 6 -out {wildcards.query}_blast_hits.tsv -threshold {bit_score}
            awk '{{print $2}}' {wildcards.query}_blast_hits.tsv > {wildcards.query}_blast_hits_ids.txt
            blastdbcmd -db {wildcards.query}_blast_db -entry_batch {wildcards.query}_blast_hits_ids.txt > {wildcards.query}_blast_hits.fasta
           """

rule cd_hit_cluster_hits:
    input: lambda wildcards: f"{wildcards.query}/{wildcards.query}_blast_hits.fasta"
    output: "{query}/{query}_blast_hits_clust.fasta"
    benchmark: "benchmarks/cd_hit_cluster_hits_{query}.txt"
    conda: "pia3.yml"
    log: "logs/cd_hit_cluster_hits_{query}.txt"
    threads: 8
    params: c=cd_h,
            n=5,
            M=2000
    shell: """
            cd {wildcards.query}
            cd-hit -i {wildcards.query}_blast_hits.fasta -o {wildcards.query}_blast_hits_clust.fasta -c {params.c} -n {params.n} -M {params.M} -T {threads}
            """

rule rename_and_filter_hits:
    input: lambda wildcards: f"{wildcards.query}/{wildcards.query}_blast_hits_clust.fasta"
    output: "{query}/{query}_blast_hits_clust_renamed.fasta"
    benchmark: "benchmarks/rename_and_filter_hits_{query}.txt"
    conda: "pia3.yml"
    log: "logs/rename_and_filter_hits_{query}.txt"
    threads: 2
    shell: "python3 /home/akizenko/Apps/pia3_amphipod_opsins/PIA3/scripts/rename_hits.py {db} {input} {output} {wildcards.query} {transcripts}"


rule calculate_mad_distances:
    input: "db_align.fasta.contree"
    output: "mad_distances_db_contree.txt"
    benchmark: "benchmarks/calculate_mad_distances.txt"
    conda: "pia3.yml"
    log: "logs/calculate_mad_distances.txt"
    threads: 1
    shell: "python3 /home/akizenko/Apps/pia3_amphipod_opsins/PIA3/scripts/calc_mean_dist.py {input} {output}"


rule mafft_align_db_query_seqs:
    input: db = db, query_seqs = "{query}/{query}_blast_hits_clust_renamed.fasta"
    output: "{query}/{query}_db_align.fasta"
    #benchmark: "benchmarks/mafft_align_query_seqs_{query}.txt"
    conda: "pia3.yml"
    #log: "logs/mafft_align_query_seqs_{query}.txt"
    threads: 8
    shell: """
        cat {input.db} {input.query_seqs} > {wildcards.query}/db_query.fasta
        mafft --thread {threads} --auto {wildcards.query}/db_query.fasta > {output}
        """

# rule iqtree_build_db_query_tree:
#     input: "db_align.fasta"
#     output: "db_align.fasta.contree"
#     benchmark: "benchmarks/iqtree_build_db_tree.txt"
#     conda: "pia3.yml"
#     log: "logs/iqtree_build_db_tree.txt"
#     params: bb=1000,
#             model="'LG+F+G4'",
#             nt="AUTO",
#             t="RANDOM"
#     threads: 8
#     shell: "iqtree -s {input} -nt {params.nt} -t {params.t} -bb {params.bb} -m {params.model} 2> {log}"

# rule pia_analysis:
#     input: ref=lambda wildcards: f"{in_dir}/{wildcards.reference}",
#            tree=rules.build_initial_tree.output.tree
#     output: ref_out_dir=directory("{out_dir}/{reference}")
#     conda: "config/opsins.yml"
#     benchmark: "{out_dir}/benchmarks/pia_{reference}.txt"
#     log: "{out_dir}/logs/pia_{reference}.txt"
#     params: args=' '.join(pia_args), db=db, model=model, outgroup=outgroup, cd_h=cd_h, aligner=aligner
#     threads: 8
#     message: """
#              Start PIA analysis, input reference: {input.ref}, input tree: {input.tree},
#              db = {params.db}, parameters: {params.args}, model: {params.model}, outgroup: {outgroup}, aligner: {aligner}, cd_h: {params.cd_h}
#              """
#     shell: """
#            python3 PIA3.py -i {input.ref} -o {output.ref_out_dir} -db {params.db} \
#            -in_phylo {input.tree} -model {params.model} -outgroup {params.outgroup} -aligner {params.aligner} -cd_h {params.cd_h} {params.args} 2> {log}
#            """